version: '3.8'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge